name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install paho-mqtt
        pip install pytest
        sudo apt install php-cli php-json php-mbstring php-xml php-pcov php-xdebug

    - name: Test with pytest
      run: |
        cd tests && pytest
        cd

    - name: Test with PHPUnit
      run: |
        cd tests/testPHP && ./phpunit.phar FileClassTest.php
        cd

    - name: Docker Login
      uses: docker/login-action@v3
      with :
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Docker Build and Push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/isa:latest
